### ISSUE TITLE
Validate Type against installed reports

### ISSUE THREAD

**Issue by ITblacksheep** [tpcarman/As-Built-Report#14]
**Is your feature request related to a problem? Please describe.**
Currently the document is only checked to see if its null or empty.

**Describe the solution you'd like**
Check the report path and verify against installed reports.

**Describe alternatives you've considered**

**Additional context**

**Comment by tpcarman** [comment]
Thanks @ITblacksheep 
I had been looking at using Dynamic ValidateSet for this but had not got that far yet. Do you think you could amend your PR to do this with Styles also?

**Comment by ITblacksheep** [comment]
I can either amend the PR or create another feature request for that and add it. Let me know what you would like me to do.

**Comment by tpcarman** [comment]
Either / or I don't mind, but thanks for contributing, this was one of the first things I wanted someone to fix. Good job.

**Comment by ITblacksheep** [comment]
I added a new Feature Request.

**Comment by ITblacksheep** [comment]
Added pull request #23

**Comment by ryan-jan** [comment]
Merged #23 so closing issue.
