### ISSUE TITLE
Validate Style Sheets dynamically

### ISSUE THREAD

**Issue by ITblacksheep** [tpcarman/As-Built-Report#17]
**Is your feature request related to a problem? Please describe.**
Validate Style Sheet dynamically.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ITblacksheep** [comment]
@tpcarman Do you want it per report or in the overall New-AsBuiltReport?

**Comment by tpcarman** [comment]
Overall New-AsBuiltReport, providing the same functionality that the 'Format` parameter provides in that the parameter entry is validated and can be tab completed.

**Comment by ITblacksheep** [comment]
I was going to verify that the report path exist. Does PScribo allow you to verify the style is correct?

**Comment by tpcarman** [comment]
PScribo is kind of irrelevant in this case. `New-AsBuiltReport.ps1` has a parameter which simply calls the Style `.ps1` script and applies the styles to the document. So I was wanting to validate that the style specified `-StyleName MyCustomStyle` actually exists in the Style folder.

**Comment by ITblacksheep** [comment]
Ok I can do that one. That is just a test path. I was looking at Dynamic Parameters for the other pull request, but it wasn't actually validating the script. I think its because those are more for Functions not script parameters.

**Comment by tpcarman** [comment]
Yeah I was a bit boggled by Dynamic ValidateSet which is why I left it for someone else who has more knowledge and ability than me.

**Comment by ITblacksheep** [comment]
It may work on 6.0 but 5.1 isn't the greatest. I could validate in the begin {} code but that kind of defeats the purpose.

**Comment by tpcarman** [comment]
This repository will be archived and this issue closed. The new repository is available [here](https://github.com/AsBuiltReport/)
