### ISSUE TITLE
Feature Request: To add HBA/NIC Drivers, Firmware, Version etc.

### ISSUE THREAD

**Issue by vtrimi** [tpcarman/As-Built-Report#19]
**Feature request** to add the HBA/NIC Drivers, Firmware, Version in to the script.

.HBA-Model (16GB FC to PCI-Express-HBA )
.HBA-Device (vmhba)
.HBA-Driver (lpfcxxx)
.HBA-Firmware-Version
.HBA-WWPN
.VendorName: MassStorageController
.vid / did / svid / ssid

.NIC-Model (10GB )
.NIC-Device (vmnic)
.NIC-Driver
.NIC-Firmware-Version
.DeviceClass: NetworkController
.vid / did / svid / ssid

**Comment by tpcarman** [comment]
@edmsanchez @arielsanchezmora I know you guys have brought this to your [vDocumentation](https://github.com/arielsanchezmora/vDocumentation) project, any interest in also contributing it to ours? We do however limit the number of required PowerShell modules to 2 (PScribo & PowerCLI) so we would need to see how we can pull this into a function or existing code.

**Comment by arielsanchezmora** [comment]
Heck yeah! That's what open source is all about. You should be able to find it in the Get-esxIOdevice module, and it doesn't require anything but powercli to gather the data.

https://github.com/arielsanchezmora/vDocumentation/blob/master/powershell/vDocumentation/Public/Get-ESXIODevice.ps1

**Comment by edmsanchez** [comment]
Absolutely!. I watched your VMworld session; very, very cool stuff. I'm looking to test your solution in my environment when i'm able to get some free cycles :). Any way we can contribute, you can count on it.

**Comment by tpcarman** [comment]
Issue addressed in commit https://github.com/tpcarman/As-Built-Report/commit/2e34306b26ed8219d2f18a2bb4ee76e2cb1c5552
