### ISSUE TITLE
vSphere.ps1 using deprecated CmdLets and properties.

### ISSUE THREAD

**Issue by ryan-jan** [tpcarman/As-Built-Report#20]
This issue is to detail each of the deprecated CmdLets and/or object properties that the vSphere.ps1 script is currently using. These sections will be reworked and the deprecated items will be replaced.

- WARNING: PowerCLI scripts should not use the 'DatastoreIdList' property of VMHost type. The property will be removed in
 a future release.
- WARNING: The 'VirtualSwitch' property of VMHostNetworkInfo type is deprecated. Use 'Get-VirtualSwitch' cmdlet instead.
- WARNING: The 'VirtualNic' property of VMHostNetworkInfo type is deprecated. Use 'Get-VMHostNetworkAdapter' cmdlet
instead.
- WARNING: The 'PhysicalNic' property of VMHostNetworkInfo type is deprecated. Use 'Get-VMHostNetworkAdapter' cmdlet
instead.
- WARNING: The 'Accessible' property of Datastore type is deprecated. Use the 'State' property instead.
- WARNING: The 'Version' property of VirtualMachine type is deprecated. Use the 'HardwareVersion' property instead.

**Comment by tpcarman** [comment]
Issue resolved in PR https://github.com/tpcarman/As-Built-Report/pull/67
