### ISSUE TITLE
Update vSphere.ps1 to include Summary InfoLevel 1 information

### ISSUE THREAD

**Issue by tpcarman** [tpcarman/As-Built-Report#21]
Is your feature request related to a problem? Please describe.
Currently the `vSphere.ps1` script lacks summarised information for each section.

Describe the solution you'd like
Add additional code which aligns to InfoLevel 1 to provide summary information for each section

Describe alternatives you've considered

Additional context

**Comment by mbangdiwala** [comment]
Thanks a billion to share such a awesome script with us, I Ran the same where it took just 77 minutes to fetch 3000VM/200 ESXi Hosts/415 datastores/ 98 PG etc. It's works well for all components just have 2 queries.

-This script is not fetching/collecting data for SRM component.
-We have NetAPP all flash array storage, will this script work with NetAPP AFA storage, if yes. What all data it will collect and if possible if you have sample report please share the same 

Thank You

**Comment by tpcarman** [comment]
Hi @mbangdiwala, 

SRM reporting is on the roadmap for the vSphere report. The SRM InfoLevel you see in the `vSphere.json` file is a placeholder as documented [here](https://github.com/tpcarman/As-Built-Report/blob/dev/Reports/vSphere/README.md).

We don't have a NetApp report at the moment, however someone has just volunteered today to start building this.

**Comment by ryan-jan** [comment]
Hi,

Please can you create a separate issue for this question, or better still chat to us in the VMware Code slack channel `#as-built-report` thanks.

**Comment by ryan-jan** [comment]
I am currently working on refactoring the Datastore Cluster and Datastore sections to include InfoLevel 1 information.

**Comment by tpcarman** [comment]
Moved to [new repository](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/issues/30)
