### ISSUE TITLE
Firewall allowed IP

### ISSUE THREAD

**Issue by iron-2** [tpcarman/As-Built-Report#22]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the Firewall section view the allowed IP addresses if "Not All" is allowed.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mattallford** [comment]
Hi @iron-2,

Are you talking about the ESXi Firewall or NSX section? And if NSX, the DFW or the Edge FW?

I've recently refactored some of the code that pulls the firewall rules for the DFW. I still have a couple of minor issues to fix, but I'd appreciate if you can update from the dev repository and rerun the script, and report back any anomalies you see. I think the main thing I still need to fix is capturing multiple objects in source/destination correctly, which I'm hoping to work on over the weekend.

Cheers, Matt.

**Comment by mattallford** [comment]
Hi @iron-2,

Just touching base on this again. I've made some modifications to the DFW section for NSX. Can you re-test to see if this is still an issue or not?

Cheers, Matt.

**Comment by mattallford** [comment]
It's been over 2 weeks with no response, and I believe the issue is resolved.

@tpcarman / @ryan-jan can you please close this issue?
