### ISSUE TITLE
Refactor scripts into a PowerShell module.

### ISSUE THREAD

**Issue by ryan-jan** [tpcarman/As-Built-Report#25]
Plan to refactor these scripts into a full PowerShell module. This will allow us to host the module on PSGallery.

This will take quite a bit of work and therefore I propose that in the first instance we only convert/export the `New-AsBuiltReport` function, leaving each of the reports as standard scripts. This actually ends up being a pretty minor tweak which enables us to proceed with things like hosting on PSGallery. I will submit a PR to demo this for people to test. 

Then moving forward we would need to decide how we want to tackle converting the report scripts to advanced functions ready to be exported by the module. This throws up some issues as currently the specified report is called by building the path to the script file using the `-Type` parameter as below.

```
# Generate report
    if ($Type) {
        $ScriptFile = "$PSScriptRoot\Reports\$Type\$Type.ps1"
        if (Test-Path $ScriptFile -ErrorAction SilentlyContinue) {
            .$ScriptFile
        }
        else {
            Write-Error "$Type report does not exist"
            break
        }
    }
```
And a similar thing is happening to set the styles. This will have to change and it would be good to discuss ideas for resolving this below.

**Comment by ryan-jan** [comment]
PR #30 has implemented the first stage of this plan. `New-AsBuiltReport.ps1` has now been turned into a function and is exported by the `AsBuiltReport.psm1` file. 

Next steps are to investigate the best way to convert the report scripts into advanced functions to also be exported by the `AsBuiltReport.psm1` file.

**Comment by tpcarman** [comment]
Completed
