### ISSUE TITLE
NSX NAT output shows no content. 

### ISSUE THREAD

**Issue by mhadfield-au** [tpcarman/As-Built-Report#28]
**Describe the bug**
vSphere.json has "NSX": 5 defined. Same effect with "NSX": 3
Output is defined to be a Word document. 

When running the report against a vSphere with NSX deployment that has lots of ESGWs configured, the NSX report does not correctly list the NAT configurations. Instead it produces a 2 column table with a single entry of "natRules" in it. 

Other NSX configuration information is being collected and is correct. 

**To Reproduce**
1. Configure the vSphere.json file to report on NSX objects. 
2. Configure at least one ESGW with NAT rules. 
3. Run the report with output set to Word
4. Error appears in the tables in the "NAT Settings" table produced for each ESGW. 

**Expected behavior**
I have 7 NAT rules listed in my ESGW (With many other ESGWS). I can clearly see them in vCenter and they are functioning. I would expect that the NAT Settings table would have a list of NATs that are defined on each ESGW. 

**Screenshots**

Word document output. 
![image](https://user-images.githubusercontent.com/32364585/45337746-f305ce80-b5cc-11e8-9479-28846b4d6679.png)

This is what is seen in the ESGW configuration. 
![image](https://user-images.githubusercontent.com/32364585/45337916-db7b1580-b5cd-11e8-9545-4c0e57346831.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Powershell Version 5.0.10240.17443

**Additional context**

**Comment by mattallford** [comment]
Hi there,

Thanks for raising this issue, I actually knew about it but hadn't got around to submitting the PR to fix it. I've tweaked the script to get the NAT rules, here is an example of a SNAT and DNAT rule on an ESG being captured in the report:

![image](https://user-images.githubusercontent.com/16998139/45338746-1aab6580-b5d2-11e8-992f-ee819ed6194b.png)

I'll tidy up the code and headings a bit hopefully this evening and submit a PR to the project to resolve.

Cheers, Matt.

**Comment by ryan-jan** [comment]
Closed by PR #31
