### ISSUE TITLE
Include additional VM detailed information

### ISSUE THREAD

**Issue by tpcarman** [tpcarman/As-Built-Report#29]
**Is your feature request related to a problem? Please describe.**
Include additional configuration information for VM InfoLevel 3 and above.

**Describe the solution you'd like**
Include additional VM hardware configuration information such as SCSI controllers, NIC adapters, etc.
Include related objects such as datastores, networks etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by ryan-jan** [comment]
Merged #27 closing this issue.
