### ISSUE TITLE
Document required permissions level for vSphere report

### ISSUE THREAD

**Issue by nabarry** [tpcarman/As-Built-Report#36]
**Describe the bug**
the vsphere readme.MD should include necessary permissions prerequisites for the vSphere report. Example use case is running an automated report using a cronjob on powercli core for audit/compliance purposes, where we would not want the job running as our standard personal administrative accounts.

**Comment by ryan-jan** [comment]
Just to check I'm understanding you correctly. Do you mean we should detail the exact vSphere permissions required for a particular user account to be able to run the report?

**Comment by nabarry** [comment]
Correct.

**Comment by ryan-jan** [comment]
Perfect, I think that is a sensible idea. I'll take at look when I get a chance. Thanks for the suggestion.

**Comment by tpcarman** [comment]
This repository has been [moved](https://github.com/AsBuiltReport/) and an README available [here](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/blob/master/README.md)
