### ISSUE TITLE
problem running on MacOS, PresentationCore.dll missing

### ISSUE THREAD

**Issue by laurentsd** [tpcarman/As-Built-Report#39]
I installed Powershell 6, Pscribo and As-Built-Report on my MacBook High Sierra.
I try to run the following vSphere report script:

./New-AsBuiltReport.ps1 -Target <IP> -Username administrator@vsphere.local -Password <PWD> -Type vSphere -Format TEXT -Timestamp -Path '/Users/dev/projects' -Healthchecks

and get this error about PresentationCore.dll missing.  Any idea how to deal with that on MacOS?
Thanks!

VERBOSE: [ 09:53:40:888 ] [ Document ] - Document 'VMware vSphere As Built Report - 2018-09-20_09.53.30' processing started.                             hen try the command again.
Add-Type : Cannot find path '/Users/dev/projects/As-Built-Report-dev/PresentationCore.dll' because it does not exist.
At /Users/dev/projects/As-Built-Report-dev/Styles/VMware.ps1:2 char:5
+     Add-Type -AssemblyName "PresentationCore"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (/Users/dev...presentationCore.dll:String) [Add-Type], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.AddTypeCommand

Unable to find type [Windows.Media.Fonts].
At /Users/dev/projects/As-Built-Report-dev/Styles/VMware.ps1:4 char:9
+ $Font = [Windows.Media.Fonts]::SystemFontFamilies | Where-Object {$_. ...
+         ~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Windows.Media.Fonts:TypeName) [], RuntimeException
+ FullyQualifiedErrorId : TypeNotFound

**Comment by tpcarman** [comment]
Hi @laurentsd,

This issue relates to the VMware style script, it looks for Windows fonts installed which are obviously not installed on your Mac. I will need to update and remove this to have it work in PS Core. In the meantime, to test, you can either edit the `VMware.ps1` file in the Styles folder or specify another Style by using the `-StyleName` parameter.

**Comment by tpcarman** [comment]
Try modifying `VMware.ps1` to this and let me know how it goes.

```#region VMware Document Style
    DocumentOption -EnableSectionNumbering -PageSize A4 -DefaultFont Arial -MarginLeftAndRight 71 -MarginTopAndBottom 71

    Style -Name 'Title' -Size 24 -Color '002538' -Align Center
    Style -Name 'Title 2' -Size 18 -Color '007CBB' -Align Center
    Style -Name 'Title 3' -Size 12 -Color '007CBB' -Align Left
    Style -Name 'Heading 1' -Size 16 -Color '007CBB' 
    Style -Name 'Heading 2' -Size 14 -Color '007CBB' 
    Style -Name 'Heading 3' -Size 12 -Color '007CBB' 
    Style -Name 'Heading 4' -Size 11 -Color '007CBB' 
    Style -Name 'Heading 5' -Size 10 -Color '007CBB'
    Style -Name 'H1 Exclude TOC' -Size 16 -Color '007CBB' 
    Style -Name 'Normal' -Size 10 -Color '565656' -Default
    Style -Name 'TOC' -Size 16 -Color '007CBB' 
    Style -Name 'TableDefaultHeading' -Size 10 -Color 'FAF7EE' -BackgroundColor '002538' 
    Style -Name 'TableDefaultRow' -Size 10 
    Style -Name 'TableDefaultAltRow' -Size 10 -BackgroundColor 'D9E4EA' 
    Style -Name 'Critical' -Size 10 -BackgroundColor 'FFB38F'
    Style -Name 'Warning' -Size 10 -BackgroundColor 'FFE860'
    Style -Name 'Info' -Size 10 -BackgroundColor 'A6D8E7'
    Style -Name 'OK' -Size 10 -BackgroundColor 'AADB1E'

    TableStyle -Id 'TableDefault' -HeaderStyle 'TableDefaultHeading' -RowStyle 'TableDefaultRow' -AlternateRowStyle 'TableDefaultAltRow' -BorderColor '002538' -Align Left -BorderWidth 0.5 -Default
    TableStyle -Id 'Borderless' -BorderWidth 0

    # VMware Cover Page
    BlankLine -Count 11
    Paragraph -Style Title $ReportName
    if ($Company.FullName) {
        Paragraph -Style Title2 $Company.FullName
        BlankLine -Count 27
        Table -Name 'Cover Page' -List -Style Borderless -Width 0 -Hashtable ([Ordered] @{
                'Author:'  = $Author
                'Date:'    = Get-Date -Format 'dd MMMM yyyy'
                'Version:' = $Version
            })
        PageBreak
    }
    else {
        BlankLine -Count 28
        Table -Name 'Cover Page' -List -Style Borderless -Width 0 -Hashtable ([Ordered] @{
                'Author:'  = $Author
                'Date:'    = Get-Date -Format 'dd MMMM yyyy'
                'Version:' = $Version
            })
        PageBreak
    }
}

# Table of Contents
TOC -Name 'Table of Contents'
PageBreak
```

**Comment by laurentsd** [comment]
Thanks. Updating VMware.ps1 to remove the Windows $font test works great.

**Comment by tpcarman** [comment]
Great. I will make the necessary updates shortly. Thanks for highlighting the issue.

**Comment by tpcarman** [comment]
Issue resolved in https://github.com/tpcarman/As-Built-Report/commit/fb8d84c8aa2ae86d34960ae5143561dd9c22e994
