### ISSUE TITLE
Get-PatchBaseline requires VMware.VumAutomation

### ISSUE THREAD

**Issue by cjastone** [tpcarman/As-Built-Report#45]
**Describe the bug**
The use of `Get-PatchBaseline` requires the module `VMware.VumAutomation` to be imported.  Unless this is manually imported before running the script, the following error will be produced: 

`Get-PatchBaseline : The term 'Get-PatchBaseline' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

**To Reproduce**
Run the script - errors will be observed.
Run `Import-Module VMware.VumAutomation` then run the script again - errors now absent.

**Expected behavior**
The script should list `VMware.VumAutomation` as a required module.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 1803, PowerShell 5.1.17134.228, PowerCLI 6.5.0.234

**Comment by ryan-jan** [comment]
Hi,

We should add `VMware.VumAutomation` to the `#requires` block for completeness.

However, I'm curious as to what version of PowerShell you are using, as since PS v3.0 modules should be implicitly imported when a CmdLet from the module is referenced ([see here](https://docs.microsoft.com/en-us/powershell/developer/module/importing-a-powershell-module#implicitly-importing-a-module-powershell-30)).

**Comment by cjastone** [comment]
Hi @ryan-jan - I'm using 5.1.17134.228 according to `$psversiontable` on W10 1803.

**Comment by tpcarman** [comment]
@cjastone Are you running the script directly from PowerShell command window or from an editor such as vscode or ISE?

**Comment by cjastone** [comment]
@tpcarman - I'm running straight from the CLI.

That said - I used it on another machine last week and didn't encounter this issue.

I did notice that was using a super old version of PowerCLI (it was the top Google result and 6.5 sounded in line with vSphere versioning.)  Could this have been the cause?

**Comment by tpcarman** [comment]
This repository is set to be archived. A [new repository](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere) has been setup for the VMware vSphere as built report.

If you are still experiencing this issue with the [updated](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/commit/f2d92ca468d781bc9464e0446fa9f4ead9973212) report, please log an issue against the new repository.
