### ISSUE TITLE
vSphere Report. Add missing vCenter Server Advanced Settings for Certificates

### ISSUE THREAD

**Issue by mc1903** [tpcarman/As-Built-Report#47]
**Is your feature request related to a problem? Please describe.**
I would like to see **all** of the 'certmgmt' settings in the vSphere report please.

**Describe the solution you'd like**
Amend the **vCenter Server SSL Certificate region** to include:

```
vpxd.certmgmt.mode 
vpxd.certmgmt.certs.hardThreshold 
vpxd.certmgmt.certs.minutesBefore 
vpxd.certmgmt.certs.pollIntervalDays 
vpxd.certmgmt.certs.softThreshold 

```

```
#region vCenter Server SSL Certificate
Section -Style Heading3 'SSL Certificate' {
    $VcSslCertHash = @{
        Country          = ($VCAdvSettings | Where-Object {$_.name -eq 'vpxd.certmgmt.certs.cn.country'}).Value
        Email            = ($VCAdvSettings | Where-Object {$_.name -eq 'vpxd.certmgmt.certs.cn.email'}).Value
        Locality         = ($VCAdvSettings | Where-Object {$_.name -eq 'vpxd.certmgmt.certs.cn.localityName'}).Value
        State            = ($VCAdvSettings | Where-Object {$_.name -eq 'vpxd.certmgmt.certs.cn.state'}).Value
        Organization     = ($VCAdvSettings | Where-Object {$_.name -eq 'vpxd.certmgmt.certs.cn.organizationName'}).Value
        OrganizationUnit = ($VCAdvSettings | Where-Object {$_.name -eq 'vpxd.certmgmt.certs.cn.organizationalUnitName'}).Value
        DaysValid        = ($VCAdvSettings | Where-Object {$_.name -eq 'vpxd.certmgmt.certs.daysValid'}).Value
        Mode             = ($VCAdvSettings | Where-Object {$_.name -eq 'vpxd.certmgmt.mode'}).Value
        HardThreshold    = ($VCAdvSettings | Where-Object {$_.name -eq 'vpxd.certmgmt.certs.hardThreshold'}).Value
        MinutesBefore    = ($VCAdvSettings | Where-Object {$_.name -eq 'vpxd.certmgmt.certs.minutesBefore'}).Value
        PollInterval     = ($VCAdvSettings | Where-Object {$_.name -eq 'vpxd.certmgmt.certs.pollIntervalDays'}).Value
        SoftThreshold    = ($VCAdvSettings | Where-Object {$_.name -eq 'vpxd.certmgmt.certs.softThreshold'}).Value
    }
        $VcSslCertificate = $VcSslCertHash | Select-Object @{L = 'Country'; E = {$_.Country}}, @{L = 'State'; E = {$_.State}}, @{L = 'Locality'; E = {$_.Locality}}, 
        @{L = 'Organization'; E = {$_.Organization}}, @{L = 'Organizational Unit'; E = {$_.OrganizationUnit}}, @{L = 'Email'; E = {$_.Email}}, @{L = 'Validity'; E = {"$($_.DaysValid / 365) Years"}},          
        @{L = 'Mode'; E = {$_.Mode}}, @{L = 'Hard Threshold'; E = {"$($_.HardThreshold) Days"}}, @{L = 'Soft Threshold'; E = {"$($_.SoftThreshold) Days"}}, 
        @{L = 'Poll Interval'; E = {"$($_.PollInterval) Days"}}, @{L = 'Minutes Before'; E = {$($_.MinutesBefore)}}
        $VcSslCertificate | Table -Name "$vCenter SSL Certificate" -List -ColumnWidths 50, 50
}
#endregion vCenter Server SSL Certificate
```

**Describe alternatives you've considered**
None; I have tested the amendments and they work just fine.

**Additional context**
![image](https://user-images.githubusercontent.com/13692287/46803108-2e73f400-cd57-11e8-8dcc-64a53b84e877.png)

**Comment by tpcarman** [comment]
Hi @mc1903,

Are you using custom SSL certificates? My original plan was to show the details of the vCenter Server certificates, however I found this code simply reported back the default certificate information. This is why I commented out this section in the report. Does it work for you? What mode are you using for certs within vCenter?

Thanks,
Tim

**Comment by mc1903** [comment]
Hi Tim,

Yes, I am using custom SSL certificates within my configuration. My VCSA VMCA is subordinate to my own internal Windows Enterprise CA. 

I understand the confusion regarding these vCenter Server 'vpxd.certmgmt' Advanced Settings, but they are still of interest (to me anyways). 

Primarily they define how the ESXi hosts certificate signing requests (CSRs) are formatted, which are then subsequently signed by the VMCA, when they (ESXi hosts) are initially joined to vCenter or when their certificates are refreshed. 

The thresholds and polling settings are also good to know. Potentially they are more interesting as a health check, to see if they have been changed from their defaults.

I too would also like to have the actual certificate information for each of the VCSA/PSC/VAMI/ESXi hosts, but I am pretty sure that data would have to be pulled directly from their respective management https:// sites.

If you decide to keep the current "SSL Certificate" report in the project you may want to rename it to something like "vCenter Certificate Management Advanced Settings", so to avoid any future confusion if there is ever a real "Server SSL Certificate" report.

This project is awesome; please keep adding to it. I am not confident with GitHub (branching/forking/pull requests/etc.) to really get involved that way and my PowerShell is still quite basic. I am more happy to test stuff tho. 

Thanks,
Martin

**Comment by tpcarman** [comment]
This repository is set to be archived. A [new repository](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere) has been created for the VMware vSphere as built report.

Please open a new feature request on the new repository.
