### ISSUE TITLE
Add more details in the vSAN section

### ISSUE THREAD

**Issue by equelin** [tpcarman/As-Built-Report#48]
**Is your feature request related to a problem? Please describe.**
This issue purpose is to request an enhancement to the vSAN section.

**Describe the solution you'd like**
Here's a first iteration of the missing informations that may be added:
- Performance Service
- Health Service
    - Configuration
    - Results
- Disk groups details
- Fault Domains
- Streched Cluster configuration
    - Witness
- Policies

I've start working at adding `Performance Service` detailed informations, here is an example of the result:

![image](https://user-images.githubusercontent.com/9823778/46869272-75331e00-ce2b-11e8-8b84-90578397c484.png)

I will submit a first PR if this feature request is approved.

**Comment by equelin** [comment]
Another example for the result of the health's tests:

![image](https://user-images.githubusercontent.com/9823778/46887024-d2939300-ce5c-11e8-8376-e98f5f9e0f36.png)

![image](https://user-images.githubusercontent.com/9823778/46887056-e63ef980-ce5c-11e8-82c8-1d1a9b8f8a88.png)

**Comment by tpcarman** [comment]
This repository is set to be archived. A [new repository](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/) has been created.
Please raise a new feature request against the new repository.
