### ISSUE TITLE
Cisco UCS Type not working

### ISSUE THREAD

**Issue by UnknownGnome** [tpcarman/As-Built-Report#49]
The Cisco UCS Type doesn't seem to be working. At first I was getting an error that I was missing the require CiscoUcsPS. I discovered that the Cisco UCS module has been renamed to Cisco.UCSManager which is what I had installed (https://community.cisco.com/t5/cisco-developed-ucs-integrations/cisco-ucs-powertool-suite-powershell-modules-for-cisco-ucs/ta-p/3639523). So I edited the requires to reflect the new module name. But then I hit an error when it tries to build the "Server Inventory" Table. 
```
Select-Object : The property cannot be processed because the property "Operability" already exists.
At C:\Users\cma503\Documents\WindowsPowerShell\Modules\As-Built-Report\Src\Public\Reports\UCS\UCS.ps1:109 char:81
+ ... D, SlotID | Select-Object @{L = 'Server Id'; E = {$_.ServerId}}, Mode ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Cisco.Ucsm.ComputeBlade:PSObject) [Select-Object], PSArgumentException
    + FullyQualifiedErrorId : AlreadyExistingUserSpecifiedPropertyNoExpand,Microsoft.PowerShell.Commands.SelectObjectCommand
```
I'm not sure how to fix that one. I also got a bunch more red errors after that one, but figured I'd start here.

**Comment by tpcarman** [comment]
Hi @UnknownGnome ,

It appears you are right, there have been changes to the UCS PowerTool. I will need to take a look to see if the new modules are backward compatible and then look at updating the report for the new module.

https://community.cisco.com/t5/cisco-developed-ucs-integrations/cisco-ucs-powertool-suite-powershell-modules-for-cisco-ucs/ta-p/3639523

Thanks for raising the issue.

**Comment by jhall12** [comment]
I have has the script "work" using the new cisco tools by modifying line 1 to the below
I am still working through some other issues with it though.

#requires -Modules @{ModuleName="PScribo";ModuleVersion="0.7.23"},Cisco.UCSManager

**Comment by tpcarman** [comment]
New Cisco UCS Manager as built report now available [here](https://github.com/AsBuiltReport/AsBuiltReport.Cisco.UcsManager)
