### ISSUE TITLE
Word and TXT file differs

### ISSUE THREAD

**Issue by iron-2** [tpcarman/As-Built-Report#50]
I appoligize if this already was addressed and I missed it going through the reports.
**Describe the bug**
In the section "Virtual Port Group NIC Teaming" the UnusedNic is missing in txt document but is there in word document.See screen shots below. In this case Vswitch 2 have Unused Nic's.
![image](https://user-images.githubusercontent.com/31862965/47797005-ca28cc80-dd25-11e8-9691-8c0d98ec81d4.png)

![image](https://user-images.githubusercontent.com/31862965/47797127-06f4c380-dd26-11e8-8817-a31efca2bfee.png)

**To Reproduce**
Run a Word and txt report 
**Expected behavior**
Same info in both documents.

**Comment by tpcarman** [comment]
Issue moved to [new repository](https://github.com/AsBuiltReport/AsBuiltReport.Core/issues/18)
