### ISSUE TITLE
Incorrect vCPU count.

### ISSUE THREAD

**Issue by karlnewick** [tpcarman/As-Built-Report#52]
**Describe the bug**

The Total vCPU count seems to be off for a VMs.

Edit setting of the VM and I see 
Number of Sockets 2
Number of cores 4
Total number of cores 8

In the report I see 

vCPUs | 8
Cores per Socket | 4 
Total vCPUs | 32

**Expected behavior**
8 Total

**Screenshots**
![image](https://user-images.githubusercontent.com/22244557/47877147-94511a00-ddf1-11e8-9fc5-19adc0e2a675.png)

This is a vSphere 5.5 environment.

**Comment by tpcarman** [comment]
Issue resolved in PR https://github.com/tpcarman/As-Built-Report/pull/67
