### ISSUE TITLE
VM information

### ISSUE THREAD

**Issue by karlnewick** [tpcarman/As-Built-Report#53]
Would it be possible to get the IP address of the VM and the Portgroup its attached too?

Amazing work guys!

**Comment by karlnewick** [comment]
I just added this and this works for the IP address

@{L = 'IP Address' ; E = {$_.guest.IPAddress[0]}},

**Comment by Midnigh7** [comment]
Edit;
Get Array of Port Groups - @{L = 'Port Group'; E = {(Get-VirtualPortGroup -VM $VM).Name | % {$_} | out-string }},
Get Array of IPs - @{L = 'IP Address'; E = {$VM.Guest.IPAddress | % {$_} | out-string }},

**Comment by tpcarman** [comment]
This repository is set to be archived. A [new repository](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere) is now available.
Please open a new feature request against the new repository
