### ISSUE TITLE
Section 1.6 vSAN not sorted clusters alphabetically

### ISSUE THREAD

**Issue by daunce** [tpcarman/As-Built-Report#54]
**Describe the bug**
Section 1.6 vSAN sub section isn't sorted alphabetically per cluster.

**To Reproduce**
1. Run report. Look at sections 1.6 vSAN
2. In my case the Management cluster was listed before the Application cluster.

**Expected behavior**
Clusters should be sorted alphabetically.

**Additional context**
Tim forced me to log this.

**Comment by tpcarman** [comment]
Issue resolved in PR https://github.com/tpcarman/As-Built-Report/pull/67
