### ISSUE TITLE
Incorrect count of hosts in section 1.6 vSAN

### ISSUE THREAD

**Issue by daunce** [tpcarman/As-Built-Report#55]
**Describe the bug**
Section 1.6 vSAN shows twice the amount of hosts in a vSAN cluster.

**To Reproduce**
1. Run report
2. Look at section 1.6 vSAN Number of Hosts

**Expected behavior**
To show actual number of hosts.

**Screenshots**
Screenshot attached.

![image 1](https://user-images.githubusercontent.com/7698573/48237990-5b322e80-e41d-11e8-9805-42201442158d.png)

**Additional context**
Tim is a bully.

**Comment by tpcarman** [comment]
Issue resolved in PR https://github.com/tpcarman/As-Built-Report/pull/67
