### ISSUE TITLE
Assess specific vSphere datacenter or cluster object

### ISSUE THREAD

**Issue by rutgerblom** [tpcarman/As-Built-Report#56]
It would be nice if one could run AsBuiltReport for a specific vSphere datacenter or cluster object only. This would be useful in larger environments that have multiple datacenter objects containing multiple clusters and where you only want to assess one particular part of the environment.

Maybe it would be possible to add something like "scope" or "location" to the .json that would narrow down the scope.

I tried to manually add the "-Location" to the different "get-" commands in the vSphere.ps1 but this broke things somehow.

**Comment by tpcarman** [comment]
This repository is set to be archived. A [new repository](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere) is now available.
Please open a new feature request against the new repository.
