### ISSUE TITLE
Config file values not honored

### ISSUE THREAD

**Issue by tquizzle** [tpcarman/As-Built-Report#57]
**Describe the bug**
When passing the `-AsBuiltConfigPath ./path/to/file.json` the vSphere report isn't respecting the values in the file.

**To Reproduce**
1. Run report `New-AsBuiltReport -Target vc.fqdn -Credentials $creds -Format HTML vSphere -Timestamp -Path ./path/to/reports/ -AsBuiltConfigPath ./Src/Public/file.json`
2. Report runs as normal (i.e. without any respect to the "InfoLevel" values I've set.)

**Expected behavior**
I expected the report to be quick as I only wanted "Summary" information on several sections.
My json listed below

**file.json**
```
  "InfoLevel": {
      "_comment_": "0 = Disabled, 1 = Summary, 2 = Informative, 3 = Detailed, 4 = Adv Detailed, 5 = Comprehensive",
      "vCenter": 1,
      "Cluster": 1,
      "ResourcePool": 0,
      "VMhost": 0,
      "Network": 0,
      "Vsan": 1,
      "Datastore": 0,
      "DSCluster": 0,
      "VM": 1,
      "VUM": 0,
      "NSX": 0,
      "SRM": 0
  },
```

What I got was a report as configured by the vSphere.json file 
**vSphere.json**
```
    "InfoLevel": {
        "_comment_": "0 = Disabled, 1 = Summary, 2 = Informative, 3 = Detailed, 4 = Adv Detailed, 5 = Comprehensive",
        "vCenter": 3,
        "Cluster": 3,
        "ResourcePool": 3,
        "VMhost": 3,
        "Network": 3,
        "Vsan": 3,
        "Datastore": 3,
        "DSCluster": 3,
        "VM": 3,
        "VUM": 3,
        "NSX": 0,
        "SRM": 0
    },
```

**Screenshots**
Report obtained:
![screen shot 2018-12-12 at 5 26 05 pm](https://user-images.githubusercontent.com/412380/49905439-49d0ad80-fe33-11e8-8f2b-47db57a8079a.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser Firefox
 - Version 63.0.3

**Comment by tpcarman** [comment]
The `vSphere.json` file cannot be specified using a parameter from the commandline. The `AsBuiltConfigPath` parameter path references the AsBuilt JSON file, which stores information relating to Author, Company and Mail settings. The location of the `vSphere.json` file is hard-coded within the vSphere report script and must reside in the `..\Reports\vSphere` folder.
