### ISSUE TITLE
Cisco UCS style sheet does not apply

### ISSUE THREAD

**Issue by jhall12** [tpcarman/As-Built-Report#58]
Cisco UCS script is still using the old way to call the Style sheet on lines 27-30 this in turns makes the Style fail to apply and does not create the Table of Contents

Current
If custom style not set, use Cisco style
if (!$StyleName) {
    .\Styles\Cisco.ps1
}

Solution
If custom style not set, use Cisco style
if (!$StyleName) {
    & "$PSScriptRoot\..\..\Styles\Cisco.ps1"
}

**Comment by tpcarman** [comment]
New Cisco UCS as built report now available [here](https://github.com/AsBuiltReport/AsBuiltReport.Cisco.UcsManager)
