### ISSUE TITLE
vSphere: Custom multipath plugins do not display

### ISSUE THREAD

**Issue by danbarr** [tpcarman/As-Built-Report#61]
**Describe the bug**
In the vSphere report, the Multipath Policy value is not populated on the report for Datastore LUNs which use a 3rd party custom PSP module (example: NIMBLE_PSP_DIRECTED for Nimble arrays).

**To Reproduce**
1. Run report against an environment with a 3rd-party PSP module in use.
2. "Multipath Module" entry in the SCSI LUN Details section will be blank.

**Expected behavior**
The PSP in use by the LUN should be displayed.

**Additional context**
The code does a lookup against the three known built-in PSP plugins to show the friendly policy name. If the actual plugin is not found, no value is returned. Propose inserting the actual value of the plugin if not found. I'll submit a PR.

**Comment by mattallford** [comment]
Resolved in #62
