### ISSUE TITLE
vSphere: Incorrect vSAN disk count and type

### ISSUE THREAD

**Issue by danbarr** [tpcarman/As-Built-Report#63]
**Describe the bug**
In the vSAN section, the Type and Total Number of Disks values are reported incorrectly. Only SSDs are counted in the number of disks, and Hybrid clusters may be reported as All-Flash.

**To Reproduce**
1. Run the report on an environment with a Hybrid vSAN cluster
2. Note the incorrect Type and Total Number of Disks

**Expected behavior**
vSAN type should report "Hybrid" and the total number of disks should include HDD capacity disks.

**Screenshots**
Report run against a Hybrid vSAN cluster; type is wrong and disk count should be 6:
![image](https://user-images.githubusercontent.com/6922515/51511351-f73dc600-1dce-11e9-80df-77e209ff0f58.png)

**Comment by tpcarman** [comment]
Issue resolved in PR https://github.com/tpcarman/As-Built-Report/pull/67
