### ISSUE TITLE
NSX uses same credentials as vCenter without prompt

### ISSUE THREAD

**Issue by RACranendonk** [tpcarman/As-Built-Report#65]
**Describe the bug**
When running the script with NSX enabled it automatically uses the credentials for vCenter in NSX. However, default CLIUser creds are admin//\<password\>. Only after adding a CLIUser through SSH and RestAPI the NSX script works.

**To reproduce**
To reproduce issue:
1. Enable NSX in the vsphere.json
2. Run the script with default users 
3. NSX script fails on `if($NSXManager){` and doesn't produce output

**To resolve**
To resolve the issue and get the script working properly:
1. SSH into NSX manager
2. Follow steps outlined in NSX documentation "Create a User with Web Interface Access Using CLI" with credentials same as used for vCenter
3. NSX script succeeds and output is created

**Expected behavior**
An error should show when the credentials fail. 

**Proposed resolution**
Prompt for NSX credentials or give the option to use the same as vCenter.

**Comment by mattallford** [comment]
Hi @RACranendonk,

Thanks for logging the bug!

The NSX report has a try / catch when connecting to NSX manager, but I need to test if this produces a terminating error.

So I’m guessing that the user you are running the report as could connect to NSX Manager but then didn’t have the privileges required to get the data, is that correct?

In a new structure of the project we are working on, the NSX report is actually a standalone report that is called independantly from the vSphere report, allowing you to specify credentials just for the NSX report only.

Would that functionality, in addition to documenting the required privileges to run the report be a good starting point?

I’ll also have a think about how we could call the NSX report from the vSphere report as an option AND allow different credentials to be specified for the vSphere component and the NSX component. Open to ideas, though!

Cheers, Matt.

**Comment by RACranendonk** [comment]
Hi Matt,

After adding some more verbosity to the try / catch it does indeed fail there. The `Write-Verbose` doesn't seem to create output though.

The user I've used for the vSphere script is the default administrator@localdomain, so that should have all the credentials needed in NSX. It's not a root admin for the NSX manager though, that's where I think the issue lies.

In the below image I've added the 'administrator' user as an NSX CLI User and gave it the same password as the vCenter administrator (following the steps in the documentation I mentioned).
![image](https://user-images.githubusercontent.com/4656220/51529380-d90cb000-1e38-11e9-9e7e-4b8fe4d809ba.png)
Please note that it is labelled as 'Auditor' where it's actually created as super_user.

Running NSX as a standalone report would work just fine I think, as long as there's an option to specify different credentials for that component.

Currently in the NSX script on line 29 it gets the `[PSCredential]$Credentials` passed from the pipeline. I'm not proficient with PowerShell in any way, but I think that's where the issue starts.

Great work on the tool! Really appreciate the effort and it'll make my life a lot easier.

Regards, Robert

**Comment by tpcarman** [comment]
Issue moved to [new repository](https://github.com/AsBuiltReport/AsBuiltReport.VMware.NSXv/issues/8)
