### ISSUE TITLE
vSphere Report. Reduce repetitiveness for Advanced Host settings and Software VIBs sections 

### ISSUE THREAD

**Issue by mc1903** [tpcarman/As-Built-Report#66]
**Is your feature request related to a problem? Please describe.**
Repeating the ESXi Host Advanced System Settings & ESXi Host Software VIBs sections for each host adds 100's of pages to an InfoLevel 5 report.

**Describe the solution you'd like**
Remove the ESXi Host Advanced System Settings & ESXi Host Software VIBs from the individual ESXi Host sections and create a new 'All Hosts' report section (poss by Cluster),  where each of the settings are compared & then consolidated to either one line per value (where all hosts match) or to two or more lines (where one or more hosts has different settings). 

This would drastically reduce the report size for those of us who like the completeness of InfoLevel 5 reports. In the 3 host example below there is a 33% reduction in identical repeated lines..

Also, putting all of these settings in one place makes it considerably easier to compare settings across all hosts.

**Describe alternatives you've considered**
Not using InfoLevel 5 :-(

**Additional context**
Example:

_Current_

![image](https://user-images.githubusercontent.com/13692287/51542220-9e177600-1e52-11e9-916a-d85382be6be3.png)

_Proposed_

![image](https://user-images.githubusercontent.com/13692287/51542249-b1c2dc80-1e52-11e9-8b65-e471127f8ed7.png)

**Comment by tpcarman** [comment]
Not currently a project priority. Closing this issue as this repository is going to be archived.
