### ISSUE TITLE
The script 'NSX.ps1' cannot be run because the following modules that are specified by the "#requires

### ISSUE THREAD

**Issue by zkilany** [tpcarman/As-Built-Report#68]
When NSX is selected I'm getting the following error, PowerNSX is already installed.
. : The script 'NSX.ps1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: PowerNSX.
At D:\As-Built-Report-master\Reports\vSphere\vSphere.ps1:3087 char:22
+                     .$NSXReport -VIServer $VIServer -Credentials $Cre ...
+                      ~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (NSX.ps1:String) [], ScriptRequiresException
    + FullyQualifiedErrorId : ScriptRequiresMissingModules

**Comment by tpcarman** [comment]
Issue moved to [new repository](https://github.com/AsBuiltReport/AsBuiltReport.VMware.NSXv/issues/9)
