### ISSUE TITLE
Add Support for vRealize Automation

### ISSUE THREAD

**Issue by kclinden** [tpcarman/As-Built-Report#72]
**Is your feature request related to a problem? Please describe.**
Similar to vSphere, vRealize Automation has a lot of configurable settings that can be hard to document or track. Automating the generation of As-Built reports via PowerShell would be awesome. 

**Describe the solution you'd like**
Gather data for the vRA Default Tenant and Sub-tenants. Leverage PowervRA or directly integrate with the REST APIs for information. 

**Describe alternatives you've considered**
Only real option is to do it manually. I have considered doing something like this, but instead of putting it directly into a word doc or HTML doc putting it into some sort of JSON or YAML data structure.

**Comment by tpcarman** [comment]
This repository is set to be archived. A [new repository](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vRA) is now available. Please raise your feature request against the new repository.
