### ISSUE TITLE
Script terminates and window is restarted

### ISSUE THREAD

**Issue by stefen7** [tpcarman/As-Built-Report#73]
The script terminates midway and reopens the Powershell window.
 Running script on a Windows 10 PC

**Comment by tpcarman** [comment]
@stefen7 Could you please provide further information? 
- What report were you attempting to run?
- Can you provide information with regards to the environment
- What error did you receive?
- What version of PowerShell are you using?
Without further information I unable diagnose and assist you with your issue.

**Comment by stefen7** [comment]
I an trying to run the As-Built Report
I am running the report on a Windows 10 Enterprise PC build 1809 with the prerequisites installed. Report is connecting to a VCenter environment version 6.0.0 build 5183551. 
No error is shown. The windows which the script is running in just closes and reopens a new one.
PSVersion is 5.1.17763.134

**Comment by tpcarman** [comment]
This may be resolved in https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/commit/f2d92ca468d781bc9464e0446fa9f4ead9973212

This repository is set to be archived. A [new repository](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/) is now available. 

Please raise a new issue against the new repository if the problem still occurs.
